name: CD Release - Webapp

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Image tag to be deployed'
        required: true
        default: 'latest'

env:
  IMAGE_REG: ghcr.io
  IMAGE_REPO: benc-uk/python-demoapp
  APP_NAME: python-demoapp
  CONTAINER_NAME: python-demoapp-container

jobs:
  deploy-to-local-vm:
    name: 'Deploy to Local VM'
    runs-on:
      - self-hosted
      - label-1

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Build Docker image'
        run: |
          docker build -t $IMAGE_REPO:$IMAGE_TAG .

      - name: 'Stop and remove existing container (if any)'
        run: |
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

      - name: 'Run Docker container'
        run: |
          docker run -d --name $CONTAINER_NAME -p 8088:80 $IMAGE_REPO:$IMAGE_TAG
