name: CD Release - Webapp

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: 'Image tag to be deployed'
        required: true
        default: 'latest'

env:
  APP_NAME: python-demoapp
  CONTAINER_NAME: python-demoapp-container

jobs:
  deploy-to-local-vm:
    name: 'Deploy to Local VM'
    runs-on: self-hosted

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Validate IMAGE_TAG'
        run: |
          if [ -z "$IMAGE_TAG" ]; then
            echo "IMAGE_TAG is not set or empty, defaulting to 'latest'"
            IMAGE_TAG='latest'
          fi
          echo "Using IMAGE_TAG=$IMAGE_TAG"

      - name: 'Build Docker image locally'
        run: |
          sudo docker build -t $APP_NAME:${IMAGE_TAG:-latest} -f build/Dockerfile .


      - name: 'Stop and remove existing container (if any)'
        run: |
          sudo docker stop $CONTAINER_NAME || true
          sudo docker rm $CONTAINER_NAME || true

      - name: 'Run Docker container with local image'
        run: |
          sudo docker run -d --name $CONTAINER_NAME -p 8088:80 $APP_NAME:${IMAGE_TAG:-latest}
