name: Build and Push Docker Image

on:
  schedule:
    - cron: '15 11 28 8 *'  # Déclenche le workflow aujourd'hui à 16h30 UTC
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          push: true
          tags: tambedou/action-image:latest

      - name: Logout from Docker Hub
        run: docker logout